[project]
name = "comfyui-chunker"
description = "Itterate video chunks"
version = "1.0.0"
# license = {file = "LICENSE"}
dependencies = ["ffmpeg-python"]

[project.urls]
# Repository = "https://github.com/norgeous/comfyui-chunker"
# Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "norgeous"
DisplayName = "ComfyUI-Chunker"
